### PR TITLE
Development

### PR DESCRIPTION
**Pull request by ioilmio**
### This is a weather web app is consuming OpenWeatherMap API to get weather city's info and Pexels API for the background image;
It is built using:
- Javascript ES6
- Webpack
- Scss
- EsLint
- VsCode

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @ioilmio, great job on this project :+1: There are a few changes we need to implement to get our project approved :slightly_smiling_face: Kindly check the comments below:
- Kindly fix the scripts in the package.json. We can replace our script with 
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```
- It changes its appearance based on the received data. Currently, the appearance does not change based on the received data. Let us kindly fix that
- The use of the async/await is mixed up with the promise. Async/await goes with `try/catch` and promise goes with `then/catch`. Currently, we have mixed them up. Let us fix that
- Webpack is not configured correctly. Currently, `npm run start` outputs errors. Let us fix that
- The name of the branches and from where the PR can be improved. The PR should be from the `weather` branch to the `development` branch, not the current one we have
- I could not test the app locally because of the errors in the `npm run start` command

[OPTIONAL]
- Kindly implement a loading component that  displays from the time the form is submitted until the information comes back from the API
- It fetches the current geolocation of the user when the app is first accessed and fetches the weather from that location. Currently, it does not unless we search for our location in the search field

Once these are fixed, kindly submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by ioilmio** [comment]
Hello @addod19,
 Can you please check better?
- My `npm run start` is working correctly in my local system;
Screenshot from 2020-12-05 16-08-56

- Appearance change dynamically, when you type a city and search for it it will change the bg-image of body, weather info and temperature accordingly ;
- Using the scripts you sent me implies also have different webpack configurations one for each mode, for a small project like that I'm just using the default production mode;
- The name branch was a mistake I made, I started working on development instead  of a feature branch but the Gitflow is respected, weather is actually empty and I will merge development into weather;(is just a naming convention)
- I am using .catch() because I'm inside of a promise(fetch), I'm handling error there instead of using a try/catch for the async function; I can wrap the await call inside a try/catch block but this won't be redundant?

If I'm mistaken something please let me know, waiting for your feedback, before asking for a new review;

Slack me @illuminatosalvatore for a quick chat about these issues
Thanks for your time

Kindly Illuminato Salvatore

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
## Status: Changes Requested :red_circle: 

### Hello @ioilmio :wave: 

### I know the last TSE didn't notice this, I believe he must have forgotten, but it's a very important issue that I need to require:

- [ ] Your Pull Request is not checking for linter errors, can you please fix it?

Kindly make the requested changes and submit for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by MuriloRoque** [comment]
Hello again @ioilmio :wave: 
Your linter config is fine, can you please try opening another PR and see if it works?
Thank you! :smile:

**Comment by ioilmio** [comment]
Closing this PR because Github actions are not running properly, as suggested I'm opening a new one to fix this issue

**Pull request closed without merging**
